/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author l2001
 */
public class VistaModificarProducto extends javax.swing.JFrame {

    /**
     * Creates new form vistaCrear
     */
    public VistaModificarProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/Fuente.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBase = new javax.swing.JPanel();
        PanelSuperior = new javax.swing.JPanel();
        BotonModificar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();
        LabelNombre = new javax.swing.JLabel();
        FieldNombre = new javax.swing.JTextField();
        LabelCategoria = new javax.swing.JLabel();
        LabelCosto = new javax.swing.JLabel();
        LabelPrecioVenta = new javax.swing.JLabel();
        FieldCosto = new javax.swing.JTextField();
        FieldPrecioVenta = new javax.swing.JTextField();
        ComboBoxCategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar producto");
        setMinimumSize(new java.awt.Dimension(594, 424));
        setResizable(false);

        PanelBase.setBackground(new java.awt.Color(255, 255, 255));
        PanelBase.setPreferredSize(new java.awt.Dimension(1050, 575));

        PanelSuperior.setBackground(new java.awt.Color(249, 164, 69));

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        BotonModificar.setText("Modificar");
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarActionPerformed(evt);
            }
        });

        BotonCancelar.setText("Cancelar");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        LabelNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelNombre.setText("Nombre: ");

        FieldNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        LabelCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelCategoria.setText("Categoría:");

        LabelCosto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelCosto.setText("Costo:");

        LabelPrecioVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelPrecioVenta.setText("Precio de venta:");

        FieldCosto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FieldCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCostoActionPerformed(evt);
            }
        });

        FieldPrecioVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Alimentos", "Bebidas", "Botanas", "Dulcería", "Frutas y Verduras", "Higiene", "Vinos y Licores" }));
        ComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBaseLayout = new javax.swing.GroupLayout(PanelBase);
        PanelBase.setLayout(PanelBaseLayout);
        PanelBaseLayout.setHorizontalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelBaseLayout.createSequentialGroup()
                        .addComponent(LabelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                        .addComponent(LabelCosto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FieldCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBaseLayout.createSequentialGroup()
                        .addComponent(LabelPrecioVenta)
                        .addGap(18, 18, 18)
                        .addComponent(FieldPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                        .addComponent(LabelCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonCancelar)
                .addGap(18, 18, 18)
                .addComponent(BotonModificar)
                .addGap(41, 41, 41))
        );
        PanelBaseLayout.setVerticalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addComponent(PanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombre)
                    .addComponent(FieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxCategoria))
                .addGap(18, 34, Short.MAX_VALUE)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCosto)
                    .addComponent(FieldCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPrecioVenta)
                    .addComponent(FieldPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonModificar)
                    .addComponent(BotonCancelar))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCostoActionPerformed

    private void ComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCategoriaActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaModificarProducto().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JComboBox<String> ComboBoxCategoria;
    private javax.swing.JTextField FieldCosto;
    private javax.swing.JTextField FieldNombre;
    private javax.swing.JTextField FieldPrecioVenta;
    private javax.swing.JLabel LabelCategoria;
    private javax.swing.JLabel LabelCosto;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelPrecioVenta;
    private javax.swing.JPanel PanelBase;
    private javax.swing.JPanel PanelSuperior;
    // End of variables declaration//GEN-END:variables


    public JButton getBotonModificar() {
        return BotonModificar;
    }

    public void setBotonModificar(JButton BotonModificar) {
        this.BotonModificar = BotonModificar;
    }

    public JComboBox<String> getComboBoxCategoria() {
        return ComboBoxCategoria;
    }

    public void setComboBoxCategoria(JComboBox<String> ComboBoxCategoria) {
        this.ComboBoxCategoria = ComboBoxCategoria;
    }


    public JTextField getFieldCosto() {
        return FieldCosto;
    }

    public void setFieldCosto(JTextField FieldCosto) {
        this.FieldCosto = FieldCosto;
    }

    public JTextField getFieldNombre() {
        return FieldNombre;
    }

    public void setFieldNombre(JTextField FieldNombre) {
        this.FieldNombre = FieldNombre;
    }

    public JTextField getFieldPrecioVenta() {
        return FieldPrecioVenta;
    }

    public void setFieldPrecioVenta(JTextField FieldPrecioVenta) {
        this.FieldPrecioVenta = FieldPrecioVenta;
    }

    public JLabel getLabelCategoria() {
        return LabelCategoria;
    }

    public void setLabelCategoria(JLabel LabelCategoria) {
        this.LabelCategoria = LabelCategoria;
    }

    public JLabel getLabelCosto() {
        return LabelCosto;
    }

    public void setLabelCosto(JLabel LabelCosto) {
        this.LabelCosto = LabelCosto;
    }

    public JLabel getLabelNombre() {
        return LabelNombre;
    }

    public void setLabelNombre(JLabel LabelNombre) {
        this.LabelNombre = LabelNombre;
    }

    public JLabel getLabelPrecioVenta() {
        return LabelPrecioVenta;
    }

    public void setLabelPrecioVenta(JLabel LabelPrecioVenta) {
        this.LabelPrecioVenta = LabelPrecioVenta;
    }

    public JPanel getPanelBase() {
        return PanelBase;
    }

    public void setPanelBase(JPanel PanelBase) {
        this.PanelBase = PanelBase;
    }

    public JPanel getPanelSuperior() {
        return PanelSuperior;
    }

    public void setPanelSuperior(JPanel PanelSuperior) {
        this.PanelSuperior = PanelSuperior;
    }

    public JButton getBotonCancelar() {
        return BotonCancelar;
    }

    public void setBotonCancelar(JButton BotonCancelar) {
        this.BotonCancelar = BotonCancelar;
    }



}
