/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author l2001
 */
public class VistaAbastecerProducto extends javax.swing.JFrame {

    /**
     * Creates new form vistaCrear
     */
    public VistaAbastecerProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/Fuente.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBase = new javax.swing.JPanel();
        PanelSuperior = new javax.swing.JPanel();
        BotonAbastecer = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();
        LabelNombre = new javax.swing.JLabel();
        FieldNombre = new javax.swing.JTextField();
        LabelCodigo = new javax.swing.JLabel();
        LabelCantidad = new javax.swing.JLabel();
        FieldCodigo = new javax.swing.JTextField();
        FieldCantidad = new javax.swing.JTextField();
        BotonComprobar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar producto");
        setMinimumSize(new java.awt.Dimension(594, 424));
        setResizable(false);

        PanelBase.setBackground(new java.awt.Color(255, 255, 255));
        PanelBase.setPreferredSize(new java.awt.Dimension(1050, 575));

        PanelSuperior.setBackground(new java.awt.Color(249, 164, 69));

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        BotonAbastecer.setText("Abastecer");

        BotonCancelar.setText("Cancelar");

        LabelNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelNombre.setText("Nombre: ");

        FieldNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FieldNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FieldNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        LabelCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelCodigo.setText("Código:");

        LabelCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelCantidad.setText("Cantidad:");

        FieldCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FieldCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FieldCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        FieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCodigoActionPerformed(evt);
            }
        });

        FieldCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FieldCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCantidadActionPerformed(evt);
            }
        });

        BotonComprobar.setText("Comprobar existencia");

        javax.swing.GroupLayout PanelBaseLayout = new javax.swing.GroupLayout(PanelBase);
        PanelBase.setLayout(PanelBaseLayout);
        PanelBaseLayout.setHorizontalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonCancelar)
                    .addComponent(BotonComprobar)
                    .addGroup(PanelBaseLayout.createSequentialGroup()
                        .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelCantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LabelNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(LabelCodigo))
                        .addGap(18, 18, 18)
                        .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(FieldCantidad)
                            .addComponent(FieldCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FieldNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(BotonAbastecer)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PanelBaseLayout.setVerticalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addComponent(PanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCodigo)
                    .addComponent(FieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombre)
                    .addComponent(FieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCantidad)
                    .addComponent(FieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(BotonComprobar)
                .addGap(43, 43, 43)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAbastecer)
                    .addComponent(BotonCancelar))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCodigoActionPerformed

    private void FieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAbastecerProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAbastecerProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAbastecerProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAbastecerProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAbastecerProducto().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAbastecer;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonComprobar;
    private javax.swing.JTextField FieldCantidad;
    private javax.swing.JTextField FieldCodigo;
    private javax.swing.JTextField FieldNombre;
    private javax.swing.JLabel LabelCantidad;
    private javax.swing.JLabel LabelCodigo;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JPanel PanelBase;
    private javax.swing.JPanel PanelSuperior;
    // End of variables declaration//GEN-END:variables


    public JButton getBotonAbastecer() {
        return BotonAbastecer;
    }

    public void setBotonAbastecer(JButton BotonAbastecer) {
        this.BotonAbastecer = BotonAbastecer;
    }

    public JTextField getFieldCodigo() {
        return FieldCodigo;
    }

    public void setFieldCodigo(JTextField FieldCodigo) {
        this.FieldCodigo = FieldCodigo;
    }

    public JTextField getFieldNombre() {
        return FieldNombre;
    }

    public void setFieldNombre(JTextField FieldNombre) {
        this.FieldNombre = FieldNombre;
    }

    public JTextField getFieldCantidad() {
        return FieldCantidad;
    }

    public void setFieldCantidad(JTextField FieldCantidad) {
        this.FieldCantidad = FieldCantidad;
    }

    public JLabel getLabelCodigo() {
        return LabelCodigo;
    }

    public void setLabelCodigo(JLabel LabelCodigo) {
        this.LabelCodigo = LabelCodigo;
    }

    public JLabel getLabelNombre() {
        return LabelNombre;
    }

    public void setLabelNombre(JLabel LabelNombre) {
        this.LabelNombre = LabelNombre;
    }

    public JLabel getLabelCantidad() {
        return LabelCantidad;
    }

    public void setLabelCantidad(JLabel LabelCantidad) {
        this.LabelCantidad = LabelCantidad;
    }

    public JPanel getPanelBase() {
        return PanelBase;
    }

    public void setPanelBase(JPanel PanelBase) {
        this.PanelBase = PanelBase;
    }

    public JPanel getPanelSuperior() {
        return PanelSuperior;
    }

    public void setPanelSuperior(JPanel PanelSuperior) {
        this.PanelSuperior = PanelSuperior;
    }

    public JButton getBotonCancelar() {
        return BotonCancelar;
    }

    public void setBotonCancelar(JButton BotonCancelar) {
        this.BotonCancelar = BotonCancelar;
    }

    public JButton getBotonComprobar() {
        return BotonComprobar;
    }

    public void setBotonComprobar(JButton BotonComprobar) {
        this.BotonComprobar = BotonComprobar;
    }



}
