/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import control.ControlVentanaAdministrador;


/**
 *
 * @author l2001
 */
public class VistaVentanaAdministrador extends javax.swing.JFrame  {

    /**
     * Creates new form vistaPrincipal
     */
  
    public VistaVentanaAdministrador() {
        
        initComponents();
        this.setExtendedState(6);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/Fuente.png")).getImage());
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBase = new javax.swing.JPanel();
        PanelSuperior = new javax.swing.JPanel();
        PanelLateralIzquierdo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        LabelTitulo = new javax.swing.JLabel();
        IconoAdorno = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JButton();
        BotonAgregar = new javax.swing.JButton();
        BotonInventario = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        BotonVentas = new javax.swing.JButton();
        LabelBienvenida = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasse");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1374, 861));
        setPreferredSize(new java.awt.Dimension(1374, 861));

        PanelBase.setBackground(new java.awt.Color(255, 255, 255));
        PanelBase.setPreferredSize(new java.awt.Dimension(1050, 575));

        PanelSuperior.setBackground(new java.awt.Color(40, 82, 144));

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PanelLateralIzquierdo.setBackground(new java.awt.Color(43, 87, 154));
        PanelLateralIzquierdo.setMaximumSize(new java.awt.Dimension(200, 32767));
        PanelLateralIzquierdo.setMinimumSize(new java.awt.Dimension(200, 100));
        PanelLateralIzquierdo.setPreferredSize(new java.awt.Dimension(200, 575));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        LabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        LabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LabelTitulo.setText("Kasse");
        LabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        IconoAdorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoPanelAdministrador.png"))); // NOI18N

        BotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSalirAB.png"))); // NOI18N
        BotonSalir.setBorderPainted(false);
        BotonSalir.setMaximumSize(new java.awt.Dimension(200, 66));
        BotonSalir.setMinimumSize(new java.awt.Dimension(200, 66));
        BotonSalir.setPreferredSize(new java.awt.Dimension(200, 66));
        BotonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSalirAS.png"))); // NOI18N
        BotonSalir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSalirAB.png"))); // NOI18N
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        BotonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarAB.png"))); // NOI18N
        BotonAgregar.setBorderPainted(false);
        BotonAgregar.setMaximumSize(new java.awt.Dimension(200, 66));
        BotonAgregar.setMinimumSize(new java.awt.Dimension(200, 66));
        BotonAgregar.setPreferredSize(new java.awt.Dimension(200, 66));
        BotonAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarAS.png"))); // NOI18N
        BotonAgregar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarAB.png"))); // NOI18N
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        BotonInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAdministrarInventarioAB.png"))); // NOI18N
        BotonInventario.setBorderPainted(false);
        BotonInventario.setMaximumSize(new java.awt.Dimension(200, 66));
        BotonInventario.setMinimumSize(new java.awt.Dimension(200, 66));
        BotonInventario.setPreferredSize(new java.awt.Dimension(200, 66));
        BotonInventario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAdministrarInventarioAS.png"))); // NOI18N
        BotonInventario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAdministrarInventarioAB.png"))); // NOI18N
        BotonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInventarioActionPerformed(evt);
            }
        });

        BotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonEliminarAB.png"))); // NOI18N
        BotonEliminar.setBorderPainted(false);
        BotonEliminar.setMaximumSize(new java.awt.Dimension(200, 66));
        BotonEliminar.setMinimumSize(new java.awt.Dimension(200, 66));
        BotonEliminar.setPreferredSize(new java.awt.Dimension(200, 66));
        BotonEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonEliminarAS.png"))); // NOI18N
        BotonEliminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonEliminarAB.png"))); // NOI18N
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        BotonVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAdministrarVentasAB.png"))); // NOI18N
        BotonVentas.setBorderPainted(false);
        BotonVentas.setMaximumSize(new java.awt.Dimension(200, 66));
        BotonVentas.setMinimumSize(new java.awt.Dimension(200, 66));
        BotonVentas.setPreferredSize(new java.awt.Dimension(200, 66));
        BotonVentas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAdministrarVentasAS.png"))); // NOI18N
        BotonVentas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAdministrarVentasAB.png"))); // NOI18N
        BotonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLateralIzquierdoLayout = new javax.swing.GroupLayout(PanelLateralIzquierdo);
        PanelLateralIzquierdo.setLayout(PanelLateralIzquierdoLayout);
        PanelLateralIzquierdoLayout.setHorizontalGroup(
            PanelLateralIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLateralIzquierdoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(BotonInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelLateralIzquierdoLayout.createSequentialGroup()
                .addGroup(PanelLateralIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLateralIzquierdoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(IconoAdorno))
                    .addGroup(PanelLateralIzquierdoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(LabelTitulo)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLateralIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        PanelLateralIzquierdoLayout.setVerticalGroup(
            PanelLateralIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLateralIzquierdoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(LabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(BotonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IconoAdorno)
                .addGap(24, 24, 24))
        );

        LabelBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LabelBienvenida.setText("¡Bienvenido!");

        jScrollPane2.setBorder(null);

        TablaUsuarios.setAutoCreateRowSorter(true);
        TablaUsuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TablaUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Contraseña", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaUsuarios.setToolTipText("");
        TablaUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaUsuarios.setGridColor(new java.awt.Color(255, 255, 255));
        TablaUsuarios.setRowHeight(30);
        TablaUsuarios.setSelectionBackground(new java.awt.Color(153, 204, 255));
        TablaUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaUsuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TablaUsuarios);
        if (TablaUsuarios.getColumnModel().getColumnCount() > 0) {
            TablaUsuarios.getColumnModel().getColumn(0).setResizable(false);
            TablaUsuarios.getColumnModel().getColumn(0).setPreferredWidth(100);
            TablaUsuarios.getColumnModel().getColumn(1).setResizable(false);
            TablaUsuarios.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout PanelBaseLayout = new javax.swing.GroupLayout(PanelBase);
        PanelBase.setLayout(PanelBaseLayout);
        PanelBaseLayout.setHorizontalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addComponent(PanelLateralIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBaseLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(LabelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(875, Short.MAX_VALUE))
                    .addComponent(PanelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelBaseLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        PanelBaseLayout.setVerticalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLateralIzquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelBienvenida)
                .addGap(12, 12, 12)
                .addComponent(PanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void BotonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonInventarioActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void BotonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVentanaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonInventario;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonVentas;
    private javax.swing.JLabel IconoAdorno;
    private javax.swing.JLabel LabelBienvenida;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel PanelBase;
    private javax.swing.JPanel PanelLateralIzquierdo;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public JButton getBotonAgregar() {
        return BotonAgregar;
    }

    public void setBotonAgregar(JButton BotonAgregar) {
        this.BotonAgregar = BotonAgregar;
    }

    public JButton getBotonEliminar() {
        return BotonEliminar;
    }

    public void setBotonEliminar(JButton BotonEliminar) {
        this.BotonEliminar = BotonEliminar;
    }

    public JButton getBotonInventario() {
        return BotonInventario;
    }

    public void setBotonInventario(JButton BotonInventario) {
        this.BotonInventario = BotonInventario;
    }

    public JButton getBotonSalir() {
        return BotonSalir;
    }

    public void setBotonSalir(JButton BotonSalir) {
        this.BotonSalir = BotonSalir;
    }

    public JButton getBotonVentas() {
        return BotonVentas;
    }

    public void setBotonVentas(JButton BotonVentas) {
        this.BotonVentas = BotonVentas;
    }

    public JLabel getIconoAdorno() {
        return IconoAdorno;
    }

    public void setIconoAdorno(JLabel IconoAdorno) {
        this.IconoAdorno = IconoAdorno;
    }

    public JLabel getLabelBienvenida() {
        return LabelBienvenida;
    }

    public void setLabelBienvenida(JLabel LabelBienvenida) {
        this.LabelBienvenida = LabelBienvenida;
    }

    public JLabel getLabelTitulo() {
        return LabelTitulo;
    }

    public void setLabelTitulo(JLabel LabelTitulo) {
        this.LabelTitulo = LabelTitulo;
    }

    public JPanel getPanelBase() {
        return PanelBase;
    }

    public void setPanelBase(JPanel PanelBase) {
        this.PanelBase = PanelBase;
    }

    public JPanel getPanelLateralIzquierdo() {
        return PanelLateralIzquierdo;
    }

    public void setPanelLateralIzquierdo(JPanel PanelLateralIzquierdo) {
        this.PanelLateralIzquierdo = PanelLateralIzquierdo;
    }

    public JPanel getPanelSuperior() {
        return PanelSuperior;
    }

    public void setPanelSuperior(JPanel PanelSuperior) {
        this.PanelSuperior = PanelSuperior;
    }

    public JTable getTablaUsuarios() {
        return TablaUsuarios;
    }

    public void setTablaUsuarios(JTable TablaUsuarios) {
        this.TablaUsuarios = TablaUsuarios;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }





}
