/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JToggleButton;

/**
 *
 * @author l2001
 */
public class VistaVentanaInventarista extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public VistaVentanaInventarista() {
        initComponents();
        this.setExtendedState(6);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/Fuente.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBase = new javax.swing.JPanel();
        PanelSuperior = new javax.swing.JPanel();
        BotonSwitch = new javax.swing.JToggleButton();
        PanelLateralIzquierdo = new javax.swing.JPanel();
        BotonModificar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        LabelTitulo = new javax.swing.JLabel();
        LabelIcono = new javax.swing.JLabel();
        BotonAgregar = new javax.swing.JButton();
        BotonExcel = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonAbastecer = new javax.swing.JButton();
        LabelBienvenida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasse");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1374, 861));

        PanelBase.setBackground(new java.awt.Color(255, 255, 255));
        PanelBase.setPreferredSize(new java.awt.Dimension(1050, 575));

        PanelSuperior.setBackground(new java.awt.Color(255, 153, 51));

        BotonSwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSwitchNB.png"))); // NOI18N
        BotonSwitch.setBorder(null);
        BotonSwitch.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSwitchNDisable.png"))); // NOI18N
        BotonSwitch.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSwitchNS.png"))); // NOI18N
        BotonSwitch.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSwitchNB.png"))); // NOI18N

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanelLateralIzquierdo.setBackground(new java.awt.Color(249, 164, 69));
        PanelLateralIzquierdo.setMaximumSize(new java.awt.Dimension(200, 32767));
        PanelLateralIzquierdo.setMinimumSize(new java.awt.Dimension(200, 100));
        PanelLateralIzquierdo.setPreferredSize(new java.awt.Dimension(200, 575));

        BotonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonModificarB.png"))); // NOI18N
        BotonModificar.setBorder(null);
        BotonModificar.setBorderPainted(false);
        BotonModificar.setMaximumSize(new java.awt.Dimension(200, 66));
        BotonModificar.setMinimumSize(new java.awt.Dimension(200, 66));
        BotonModificar.setPreferredSize(new java.awt.Dimension(200, 66));
        BotonModificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonModificarS.png"))); // NOI18N
        BotonModificar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonModificarB.png"))); // NOI18N

        BotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonEliminarB.png"))); // NOI18N
        BotonEliminar.setBorderPainted(false);
        BotonEliminar.setMaximumSize(new java.awt.Dimension(200, 66));
        BotonEliminar.setMinimumSize(new java.awt.Dimension(200, 66));
        BotonEliminar.setPreferredSize(new java.awt.Dimension(200, 66));
        BotonEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonEliminarS.png"))); // NOI18N
        BotonEliminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonFactura.png"))); // NOI18N
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        LabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        LabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LabelTitulo.setText("Kasse");
        LabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoPanelInventarista.png"))); // NOI18N

        BotonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarB.png"))); // NOI18N
        BotonAgregar.setBorder(null);
        BotonAgregar.setBorderPainted(false);
        BotonAgregar.setMaximumSize(new java.awt.Dimension(200, 66));
        BotonAgregar.setMinimumSize(new java.awt.Dimension(200, 66));
        BotonAgregar.setPreferredSize(new java.awt.Dimension(200, 66));
        BotonAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarS.png"))); // NOI18N
        BotonAgregar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarB.png"))); // NOI18N

        BotonExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonExcelB.png"))); // NOI18N
        BotonExcel.setBorderPainted(false);
        BotonExcel.setMaximumSize(new java.awt.Dimension(200, 66));
        BotonExcel.setMinimumSize(new java.awt.Dimension(200, 66));
        BotonExcel.setPreferredSize(new java.awt.Dimension(200, 66));
        BotonExcel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonExcelS.png"))); // NOI18N
        BotonExcel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonExcelB.png"))); // NOI18N
        BotonExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonExcelActionPerformed(evt);
            }
        });

        BotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSalirNB.png"))); // NOI18N
        BotonSalir.setBorderPainted(false);
        BotonSalir.setMaximumSize(new java.awt.Dimension(200, 66));
        BotonSalir.setMinimumSize(new java.awt.Dimension(200, 66));
        BotonSalir.setPreferredSize(new java.awt.Dimension(200, 66));
        BotonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSalirNS.png"))); // NOI18N
        BotonSalir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSalirNB.png"))); // NOI18N
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        BotonAbastecer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAbastecerB.png"))); // NOI18N
        BotonAbastecer.setBorder(null);
        BotonAbastecer.setBorderPainted(false);
        BotonAbastecer.setMaximumSize(new java.awt.Dimension(200, 66));
        BotonAbastecer.setMinimumSize(new java.awt.Dimension(200, 66));
        BotonAbastecer.setPreferredSize(new java.awt.Dimension(200, 66));
        BotonAbastecer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAbastecerS.png"))); // NOI18N
        BotonAbastecer.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAbastecerB.png"))); // NOI18N

        javax.swing.GroupLayout PanelLateralIzquierdoLayout = new javax.swing.GroupLayout(PanelLateralIzquierdo);
        PanelLateralIzquierdo.setLayout(PanelLateralIzquierdoLayout);
        PanelLateralIzquierdoLayout.setHorizontalGroup(
            PanelLateralIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelLateralIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLateralIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(PanelLateralIzquierdoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(LabelTitulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PanelLateralIzquierdoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LabelIcono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(BotonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonAbastecer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelLateralIzquierdoLayout.setVerticalGroup(
            PanelLateralIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLateralIzquierdoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(LabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(BotonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(BotonAbastecer, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelIcono)
                .addGap(50, 50, 50))
        );

        LabelBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LabelBienvenida.setText("¡Bienvenido compañero Inventarista!");

        jScrollPane1.setBorder(null);

        TablaProductos.setAutoCreateRowSorter(true);
        TablaProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TablaProductos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Categoría", "Cantidad", "Costo", "Precio/Venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Object.class, java.lang.Short.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaProductos.setToolTipText("");
        TablaProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaProductos.setGridColor(new java.awt.Color(255, 255, 255));
        TablaProductos.setRowHeight(30);
        TablaProductos.setSelectionBackground(new java.awt.Color(255, 204, 153));
        TablaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaProductos);
        if (TablaProductos.getColumnModel().getColumnCount() > 0) {
            TablaProductos.getColumnModel().getColumn(0).setResizable(false);
            TablaProductos.getColumnModel().getColumn(1).setResizable(false);
            TablaProductos.getColumnModel().getColumn(2).setResizable(false);
            TablaProductos.getColumnModel().getColumn(3).setResizable(false);
            TablaProductos.getColumnModel().getColumn(4).setResizable(false);
            TablaProductos.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout PanelBaseLayout = new javax.swing.GroupLayout(PanelBase);
        PanelBase.setLayout(PanelBaseLayout);
        PanelBaseLayout.setHorizontalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addComponent(PanelLateralIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelBaseLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBaseLayout.createSequentialGroup()
                                .addComponent(LabelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1165, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        PanelBaseLayout.setVerticalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLateralIzquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelBienvenida)
                .addGap(18, 18, 18)
                .addComponent(PanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 1384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void BotonExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonExcelActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVentanaInventarista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVentanaInventarista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVentanaInventarista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVentanaInventarista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVentanaInventarista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAbastecer;
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonExcel;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JToggleButton BotonSwitch;
    private javax.swing.JLabel LabelBienvenida;
    private javax.swing.JLabel LabelIcono;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel PanelBase;
    private javax.swing.JPanel PanelLateralIzquierdo;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public JButton getBotonAgregar() {
        return BotonAgregar;
    }

    public void setBotonAgregar(JButton BotonAgregar) {
        this.BotonAgregar = BotonAgregar;
    }

    public JButton getBotonAbastecer() {
        return BotonAbastecer;
    }

    public void setBotonAbastecer(JButton BotonAbastecer) {
        this.BotonAbastecer = BotonAbastecer;
    }

    public JButton getBotonEliminar() {
        return BotonEliminar;
    }

    public void setBotonEliminar(JButton BotonEliminar) {
        this.BotonEliminar = BotonEliminar;
    }

    public JButton getBotonExcel() {
        return BotonExcel;
    }

    public void setBotonExcel(JButton BotonExcel) {
        this.BotonExcel = BotonExcel;
    }

    public JButton getBotonModificar() {
        return BotonModificar;
    }

    public void setBotonModificar(JButton BotonModificar) {
        this.BotonModificar = BotonModificar;
    }

    public JButton getBotonSalir() {
        return BotonSalir;
    }

    public void setBotonSalir(JButton BotonSalir) {
        this.BotonSalir = BotonSalir;
    }

    public JLabel getLabelBienvenida() {
        return LabelBienvenida;
    }

    public void setLabelBienvenida(JLabel LabelBienvenida) {
        this.LabelBienvenida = LabelBienvenida;
    }

    public JLabel getLabelIcono() {
        return LabelIcono;
    }

    public void setLabelIcono(JLabel LabelIcono) {
        this.LabelIcono = LabelIcono;
    }

    public JLabel getLabelTitulo() {
        return LabelTitulo;
    }

    public void setLabelTitulo(JLabel LabelTitulo) {
        this.LabelTitulo = LabelTitulo;
    }

    public JPanel getPanelBase() {
        return PanelBase;
    }

    public void setPanelBase(JPanel PanelBase) {
        this.PanelBase = PanelBase;
    }

    public JPanel getPanelLateralIzquierdo() {
        return PanelLateralIzquierdo;
    }

    public void setPanelLateralIzquierdo(JPanel PanelLateralIzquierdo) {
        this.PanelLateralIzquierdo = PanelLateralIzquierdo;
    }

    public JPanel getPanelSuperior() {
        return PanelSuperior;
    }

    public void setPanelSuperior(JPanel PanelSuperior) {
        this.PanelSuperior = PanelSuperior;
    }


    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JToggleButton getBotonSwitch() {
        return BotonSwitch;
    }

    public void setBotonSwitch(JToggleButton BotonSwitch) {
        this.BotonSwitch = BotonSwitch;
    }

    public JTable getTablaProductos() {
        return TablaProductos;
    }

    public void setTablaProductos(JTable TablaProductos) {
        this.TablaProductos = TablaProductos;
    }




}
