/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;

/**
 *
 * @author l2001
 */
@SuppressWarnings("rawtypes")
public class GeneralManagerView extends javax.swing.JFrame  {

    /**
     * Creates new form vistaPrincipal
     */
  
    public GeneralManagerView() {
        
        initComponents();
        this.setExtendedState(6);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/Fuente.png")).getImage());
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BasePanel = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        Separator = new javax.swing.JSeparator();
        TitleLabel = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        InventoryManagerButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        SellerButton = new javax.swing.JButton();
        WelcomeLabel = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasse");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1374, 861));
        setPreferredSize(new java.awt.Dimension(1374, 861));

        BasePanel.setBackground(new java.awt.Color(255, 255, 255));
        BasePanel.setPreferredSize(new java.awt.Dimension(1050, 575));

        TopPanel.setBackground(new java.awt.Color(40, 82, 144));

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        LeftPanel.setBackground(new java.awt.Color(43, 87, 154));
        LeftPanel.setMaximumSize(new java.awt.Dimension(200, 32767));
        LeftPanel.setMinimumSize(new java.awt.Dimension(200, 100));
        LeftPanel.setPreferredSize(new java.awt.Dimension(200, 575));

        Separator.setForeground(new java.awt.Color(255, 255, 255));

        TitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        TitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setText("Kasse");
        TitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSalirAB.png"))); // NOI18N
        LogoutButton.setBorderPainted(false);
        LogoutButton.setMaximumSize(new java.awt.Dimension(200, 66));
        LogoutButton.setMinimumSize(new java.awt.Dimension(200, 66));
        LogoutButton.setPreferredSize(new java.awt.Dimension(200, 66));
        LogoutButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSalirAS.png"))); // NOI18N
        LogoutButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSalirAB.png"))); // NOI18N
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarAB.png"))); // NOI18N
        AddButton.setBorderPainted(false);
        AddButton.setMaximumSize(new java.awt.Dimension(200, 66));
        AddButton.setMinimumSize(new java.awt.Dimension(200, 66));
        AddButton.setPreferredSize(new java.awt.Dimension(200, 66));
        AddButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarAS.png"))); // NOI18N
        AddButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarAB.png"))); // NOI18N
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        InventoryManagerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAdministrarInventarioAB.png"))); // NOI18N
        InventoryManagerButton.setBorderPainted(false);
        InventoryManagerButton.setMaximumSize(new java.awt.Dimension(200, 66));
        InventoryManagerButton.setMinimumSize(new java.awt.Dimension(200, 66));
        InventoryManagerButton.setPreferredSize(new java.awt.Dimension(200, 66));
        InventoryManagerButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAdministrarInventarioAS.png"))); // NOI18N
        InventoryManagerButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAdministrarInventarioAB.png"))); // NOI18N
        InventoryManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryManagerButtonActionPerformed(evt);
            }
        });

        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonEliminarAB.png"))); // NOI18N
        DeleteButton.setBorderPainted(false);
        DeleteButton.setMaximumSize(new java.awt.Dimension(200, 66));
        DeleteButton.setMinimumSize(new java.awt.Dimension(200, 66));
        DeleteButton.setPreferredSize(new java.awt.Dimension(200, 66));
        DeleteButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonEliminarAS.png"))); // NOI18N
        DeleteButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonEliminarAB.png"))); // NOI18N
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        SellerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAdministrarVentasAB.png"))); // NOI18N
        SellerButton.setBorderPainted(false);
        SellerButton.setMaximumSize(new java.awt.Dimension(200, 66));
        SellerButton.setMinimumSize(new java.awt.Dimension(200, 66));
        SellerButton.setPreferredSize(new java.awt.Dimension(200, 66));
        SellerButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAdministrarVentasAS.png"))); // NOI18N
        SellerButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAdministrarVentasAB.png"))); // NOI18N
        SellerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(InventoryManagerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SellerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AddButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(TitleLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Separator)
                .addContainerGap())
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InventoryManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SellerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        WelcomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        WelcomeLabel.setText("¡Bienvenido!");

        ScrollPane.setBorder(null);

        UserTable.setAutoCreateRowSorter(true);
        UserTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UserTable.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Contraseña", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UserTable.setToolTipText("");
        UserTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        UserTable.setGridColor(new java.awt.Color(255, 255, 255));
        UserTable.setRowHeight(30);
        UserTable.setSelectionBackground(new java.awt.Color(153, 204, 255));
        UserTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        UserTable.getTableHeader().setReorderingAllowed(false);
        ScrollPane.setViewportView(UserTable);
        if (UserTable.getColumnModel().getColumnCount() > 0) {
            UserTable.getColumnModel().getColumn(0).setResizable(false);
            UserTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            UserTable.getColumnModel().getColumn(1).setResizable(false);
            UserTable.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout BasePanelLayout = new javax.swing.GroupLayout(BasePanel);
        BasePanel.setLayout(BasePanelLayout);
        BasePanelLayout.setHorizontalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasePanelLayout.createSequentialGroup()
                .addComponent(LeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BasePanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(715, Short.MAX_VALUE))
                    .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BasePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ScrollPane)
                        .addContainerGap())))
        );
        BasePanelLayout.setVerticalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(BasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeLabel)
                .addGap(12, 12, 12)
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
    }//GEN-LAST:event_AddButtonActionPerformed

    private void InventoryManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryManagerButtonActionPerformed
    }//GEN-LAST:event_InventoryManagerButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void SellerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellerButtonActionPerformed
    }//GEN-LAST:event_SellerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralManagerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JPanel BasePanel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton InventoryManagerButton;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton SellerButton;
    private javax.swing.JSeparator Separator;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JTable UserTable;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables

    public JButton getBotonAgregar() {
        return AddButton;
    }

    public void setBotonAgregar(JButton BotonAgregar) {
        this.AddButton = BotonAgregar;
    }

    public JButton getBotonEliminar() {
        return DeleteButton;
    }

    public void setBotonEliminar(JButton BotonEliminar) {
        this.DeleteButton = BotonEliminar;
    }

    public JButton getBotonInventario() {
        return InventoryManagerButton;
    }

    public void setBotonInventario(JButton BotonInventario) {
        this.InventoryManagerButton = BotonInventario;
    }

    public JButton getBotonSalir() {
        return LogoutButton;
    }

    public void setBotonSalir(JButton BotonSalir) {
        this.LogoutButton = BotonSalir;
    }

    public JButton getBotonVentas() {
        return SellerButton;
    }

    public void setBotonVentas(JButton BotonVentas) {
        this.SellerButton = BotonVentas;
    }

    public JLabel getLabelBienvenida() {
        return WelcomeLabel;
    }

    public void setLabelBienvenida(JLabel LabelBienvenida) {
        this.WelcomeLabel = LabelBienvenida;
    }

    public JLabel getLabelTitulo() {
        return TitleLabel;
    }

    public void setLabelTitulo(JLabel LabelTitulo) {
        this.TitleLabel = LabelTitulo;
    }

    public JPanel getPanelBase() {
        return BasePanel;
    }

    public void setPanelBase(JPanel PanelBase) {
        this.BasePanel = PanelBase;
    }

    public JPanel getPanelLateralIzquierdo() {
        return LeftPanel;
    }

    public void setPanelLateralIzquierdo(JPanel PanelLateralIzquierdo) {
        this.LeftPanel = PanelLateralIzquierdo;
    }

    public JPanel getPanelSuperior() {
        return TopPanel;
    }

    public void setPanelSuperior(JPanel PanelSuperior) {
        this.TopPanel = PanelSuperior;
    }

    public JTable getTablaUsuarios() {
        return UserTable;
    }

    public void setTablaUsuarios(JTable TablaUsuarios) {
        this.UserTable = TablaUsuarios;
    }

    public JScrollPane getjScrollPane2() {
        return ScrollPane;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.ScrollPane = jScrollPane2;
    }

    public JSeparator getjSeparator1() {
        return Separator;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.Separator = jSeparator1;
    }





}
