/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JToggleButton;

/**
 *
 * @author l2001
 */
@SuppressWarnings("rawtypes")
public class InventoryManagerView extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public InventoryManagerView() {
        initComponents();
        this.setExtendedState(6);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/Fuente.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BasePanel = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        SwitchButton = new javax.swing.JToggleButton();
        LeftPanel = new javax.swing.JPanel();
        ModifyButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        Separator = new javax.swing.JSeparator();
        TitleLabel = new javax.swing.JLabel();
        RenameButton = new javax.swing.JButton();
        ExcelButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        WelcomeLabel = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasse");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1374, 861));
        setPreferredSize(new java.awt.Dimension(1374, 861));

        BasePanel.setBackground(new java.awt.Color(255, 255, 255));
        BasePanel.setPreferredSize(new java.awt.Dimension(1050, 575));

        TopPanel.setBackground(new java.awt.Color(255, 153, 51));

        SwitchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSwitchNB.png"))); // NOI18N
        SwitchButton.setBorder(null);
        SwitchButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSwitchNDisable.png"))); // NOI18N
        SwitchButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSwitchNS.png"))); // NOI18N
        SwitchButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSwitchNB.png"))); // NOI18N

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SwitchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SwitchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        LeftPanel.setBackground(new java.awt.Color(249, 164, 69));
        LeftPanel.setMaximumSize(new java.awt.Dimension(200, 32767));
        LeftPanel.setMinimumSize(new java.awt.Dimension(200, 100));
        LeftPanel.setPreferredSize(new java.awt.Dimension(200, 575));

        ModifyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonModificarB.png"))); // NOI18N
        ModifyButton.setBorder(null);
        ModifyButton.setBorderPainted(false);
        ModifyButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonModificarS.png"))); // NOI18N
        ModifyButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonModificarB.png"))); // NOI18N

        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonEliminarB.png"))); // NOI18N
        DeleteButton.setBorderPainted(false);
        DeleteButton.setMaximumSize(new java.awt.Dimension(200, 66));
        DeleteButton.setMinimumSize(new java.awt.Dimension(200, 66));
        DeleteButton.setPreferredSize(new java.awt.Dimension(200, 66));
        DeleteButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonEliminarS.png"))); // NOI18N
        DeleteButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonFactura.png"))); // NOI18N
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        Separator.setForeground(new java.awt.Color(255, 255, 255));

        TitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        TitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setText("Kasse");
        TitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        RenameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarB.png"))); // NOI18N
        RenameButton.setBorder(null);
        RenameButton.setBorderPainted(false);
        RenameButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarS.png"))); // NOI18N
        RenameButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarB.png"))); // NOI18N

        ExcelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonExcelB.png"))); // NOI18N
        ExcelButton.setBorderPainted(false);
        ExcelButton.setMaximumSize(new java.awt.Dimension(200, 66));
        ExcelButton.setMinimumSize(new java.awt.Dimension(200, 66));
        ExcelButton.setPreferredSize(new java.awt.Dimension(200, 66));
        ExcelButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonExcelS.png"))); // NOI18N
        ExcelButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonExcelB.png"))); // NOI18N
        ExcelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcelButtonActionPerformed(evt);
            }
        });

        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSalirNB.png"))); // NOI18N
        LogoutButton.setBorderPainted(false);
        LogoutButton.setMaximumSize(new java.awt.Dimension(200, 66));
        LogoutButton.setMinimumSize(new java.awt.Dimension(200, 66));
        LogoutButton.setPreferredSize(new java.awt.Dimension(200, 66));
        LogoutButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSalirNS.png"))); // NOI18N
        LogoutButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSalirNB.png"))); // NOI18N
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ModifyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Separator)
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(TitleLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(RenameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExcelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RenameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ExcelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        WelcomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        WelcomeLabel.setText("¡Bienvenido compañero Inventarista!");

        ScrollPane.setBorder(null);

        ProductTable.setAutoCreateRowSorter(true);
        ProductTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProductTable.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Categoría", "Cantidad", "Costo", "Precio/Venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Object.class, java.lang.Short.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductTable.setToolTipText("");
        ProductTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ProductTable.setGridColor(new java.awt.Color(255, 255, 255));
        ProductTable.setRowHeight(30);
        ProductTable.setSelectionBackground(new java.awt.Color(255, 204, 153));
        ProductTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ProductTable.getTableHeader().setReorderingAllowed(false);
        ScrollPane.setViewportView(ProductTable);
        if (ProductTable.getColumnModel().getColumnCount() > 0) {
            ProductTable.getColumnModel().getColumn(0).setResizable(false);
            ProductTable.getColumnModel().getColumn(1).setResizable(false);
            ProductTable.getColumnModel().getColumn(2).setResizable(false);
            ProductTable.getColumnModel().getColumn(3).setResizable(false);
            ProductTable.getColumnModel().getColumn(4).setResizable(false);
            ProductTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout BasePanelLayout = new javax.swing.GroupLayout(BasePanel);
        BasePanel.setLayout(BasePanelLayout);
        BasePanelLayout.setHorizontalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasePanelLayout.createSequentialGroup()
                .addComponent(LeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BasePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BasePanelLayout.createSequentialGroup()
                                .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        BasePanelLayout.setVerticalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(BasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ExcelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcelButtonActionPerformed
    }//GEN-LAST:event_ExcelButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryManagerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasePanel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton ExcelButton;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JTable ProductTable;
    private javax.swing.JButton RenameButton;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JSeparator Separator;
    private javax.swing.JToggleButton SwitchButton;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables

    public JButton getBotonAgregar() {
        return RenameButton;
    }

    public void setBotonAgregar(JButton BotonAgregar) {
        this.RenameButton = BotonAgregar;
    }

    public JButton getBotonEliminar() {
        return DeleteButton;
    }

    public void setBotonEliminar(JButton BotonEliminar) {
        this.DeleteButton = BotonEliminar;
    }

    public JButton getBotonExcel() {
        return ExcelButton;
    }

    public void setBotonExcel(JButton BotonExcel) {
        this.ExcelButton = BotonExcel;
    }

    public JButton getBotonModificar() {
        return ModifyButton;
    }

    public void setBotonModificar(JButton BotonModificar) {
        this.ModifyButton = BotonModificar;
    }

    public JButton getBotonSalir() {
        return LogoutButton;
    }

    public void setBotonSalir(JButton BotonSalir) {
        this.LogoutButton = BotonSalir;
    }

    public JLabel getLabelBienvenida() {
        return WelcomeLabel;
    }

    public void setLabelBienvenida(JLabel LabelBienvenida) {
        this.WelcomeLabel = LabelBienvenida;
    }

    public JLabel getLabelTitulo() {
        return TitleLabel;
    }

    public void setLabelTitulo(JLabel LabelTitulo) {
        this.TitleLabel = LabelTitulo;
    }

    public JPanel getPanelBase() {
        return BasePanel;
    }

    public void setPanelBase(JPanel PanelBase) {
        this.BasePanel = PanelBase;
    }

    public JPanel getPanelLateralIzquierdo() {
        return LeftPanel;
    }

    public void setPanelLateralIzquierdo(JPanel PanelLateralIzquierdo) {
        this.LeftPanel = PanelLateralIzquierdo;
    }

    public JPanel getPanelSuperior() {
        return TopPanel;
    }

    public void setPanelSuperior(JPanel PanelSuperior) {
        this.TopPanel = PanelSuperior;
    }


    public JScrollPane getjScrollPane1() {
        return ScrollPane;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.ScrollPane = jScrollPane1;
    }

    public JSeparator getjSeparator1() {
        return Separator;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.Separator = jSeparator1;
    }

    public JToggleButton getBotonSwitch() {
        return SwitchButton;
    }

    public void setBotonSwitch(JToggleButton BotonSwitch) {
        this.SwitchButton = BotonSwitch;
    }

    public JTable getProductTable() {
        return ProductTable;
    }

    public void setProductTable(JTable TablaProductos) {
        this.ProductTable = TablaProductos;
    }




}
