/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author l2001
 */
public class ModifyProductView extends javax.swing.JFrame {

    /**
     * Creates new form vistaCrear
     */
    public ModifyProductView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/Fuente.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BasePanel = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        ModifyButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        QuantityLabel = new javax.swing.JLabel();
        QuantityField = new javax.swing.JTextField();
        CategoryLabel = new javax.swing.JLabel();
        SupplierCostLabel = new javax.swing.JLabel();
        CostOfSaleLabel = new javax.swing.JLabel();
        SupplierCostField = new javax.swing.JTextField();
        CostOfSaleField = new javax.swing.JTextField();
        CategoryComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar producto");
        setMinimumSize(new java.awt.Dimension(594, 424));
        setResizable(false);

        BasePanel.setBackground(new java.awt.Color(255, 255, 255));
        BasePanel.setPreferredSize(new java.awt.Dimension(1050, 575));

        TopPanel.setBackground(new java.awt.Color(249, 164, 69));

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        ModifyButton.setText("Modificar");
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancelar");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        NameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NameLabel.setText("Nombre: ");

        NameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        QuantityLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        QuantityLabel.setText("Cantidad: ");

        QuantityField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CategoryLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CategoryLabel.setText("Categoría:");

        SupplierCostLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SupplierCostLabel.setText("Costo:");

        CostOfSaleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CostOfSaleLabel.setText("Precio de venta:");

        SupplierCostField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SupplierCostField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierCostFieldActionPerformed(evt);
            }
        });

        CostOfSaleField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Alimentos", "Bebidas", "Botanas", "Dulcería", "Frutas y Verduras", "Higiene", "Vinos y Licores" }));
        CategoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BasePanelLayout = new javax.swing.GroupLayout(BasePanel);
        BasePanel.setLayout(BasePanelLayout);
        BasePanelLayout.setHorizontalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BasePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BasePanelLayout.createSequentialGroup()
                        .addComponent(NameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasePanelLayout.createSequentialGroup()
                        .addComponent(QuantityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(QuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasePanelLayout.createSequentialGroup()
                        .addComponent(SupplierCostLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SupplierCostField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BasePanelLayout.createSequentialGroup()
                        .addComponent(CostOfSaleLabel)
                        .addGap(18, 18, 18)
                        .addComponent(CostOfSaleField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasePanelLayout.createSequentialGroup()
                        .addComponent(CategoryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelButton)
                .addGap(18, 18, 18)
                .addComponent(ModifyButton)
                .addGap(41, 41, 41))
        );
        BasePanelLayout.setVerticalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasePanelLayout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CategoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityLabel)
                    .addComponent(QuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierCostLabel)
                    .addComponent(SupplierCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CostOfSaleLabel)
                    .addComponent(CostOfSaleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifyButton)
                    .addComponent(CancelButton))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SupplierCostFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierCostFieldActionPerformed
    }//GEN-LAST:event_SupplierCostFieldActionPerformed

    private void CategoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryComboBoxActionPerformed
    }//GEN-LAST:event_CategoryComboBoxActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButtonActionPerformed
    }//GEN-LAST:event_ModifyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyProductView().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasePanel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox<String> CategoryComboBox;
    private javax.swing.JLabel CategoryLabel;
    private javax.swing.JTextField CostOfSaleField;
    private javax.swing.JLabel CostOfSaleLabel;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField QuantityField;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JTextField SupplierCostField;
    private javax.swing.JLabel SupplierCostLabel;
    private javax.swing.JPanel TopPanel;
    // End of variables declaration//GEN-END:variables

    public JPanel getBasePanel() {
        return BasePanel;
    }

    public void setBasePanel(JPanel BasePanel) {
        this.BasePanel = BasePanel;
    }

    public JButton getCancelButton() {
        return CancelButton;
    }

    public void setCancelButton(JButton CancelButton) {
        this.CancelButton = CancelButton;
    }

    public JComboBox<String> getCategoryComboBox() {
        return CategoryComboBox;
    }

    public void setCategoryComboBox(JComboBox<String> CategoryComboBox) {
        this.CategoryComboBox = CategoryComboBox;
    }

    public JLabel getCategoryLabel() {
        return CategoryLabel;
    }

    public void setCategoryLabel(JLabel CategoryLabel) {
        this.CategoryLabel = CategoryLabel;
    }

    public JTextField getCostOfSaleField() {
        return CostOfSaleField;
    }

    public void setCostOfSaleField(JTextField CostOfSaleField) {
        this.CostOfSaleField = CostOfSaleField;
    }

    public JLabel getCostOfSaleLabel() {
        return CostOfSaleLabel;
    }

    public void setCostOfSaleLabel(JLabel CostOfSaleLabel) {
        this.CostOfSaleLabel = CostOfSaleLabel;
    }

    public JButton getModifyButton() {
        return ModifyButton;
    }

    public void setModifyButton(JButton ModifyButton) {
        this.ModifyButton = ModifyButton;
    }

    public JTextField getNameField() {
        return NameField;
    }

    public void setNameField(JTextField NameField) {
        this.NameField = NameField;
    }

    public JLabel getNameLabel() {
        return NameLabel;
    }

    public void setNameLabel(JLabel NameLabel) {
        this.NameLabel = NameLabel;
    }

    public JTextField getQuantityField() {
        return QuantityField;
    }

    public void setQuantityField(JTextField QuantityField) {
        this.QuantityField = QuantityField;
    }

    public JLabel getQuantityLabel() {
        return QuantityLabel;
    }

    public void setQuantityLabel(JLabel QuantityLabel) {
        this.QuantityLabel = QuantityLabel;
    }

    public JTextField getSupplierCostField() {
        return SupplierCostField;
    }

    public void setSupplierCostField(JTextField SupplierCostField) {
        this.SupplierCostField = SupplierCostField;
    }

    public JLabel getSupplierCostLabel() {
        return SupplierCostLabel;
    }

    public void setSupplierCostLabel(JLabel SupplierCostLabel) {
        this.SupplierCostLabel = SupplierCostLabel;
    }

    public JPanel getTopPanel() {
        return TopPanel;
    }

    public void setTopPanel(JPanel TopPanel) {
        this.TopPanel = TopPanel;
    }
    
    

}
