/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author l2001
 */
@SuppressWarnings("rawtypes")
public class SellerView extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public SellerView() {
        initComponents();
        this.setExtendedState(6);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/Fuente.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BasePanel = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        Separator = new javax.swing.JSeparator();
        TitleLabel = new javax.swing.JLabel();
        CodeLabel = new javax.swing.JLabel();
        QuantityLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        QuantityField = new javax.swing.JTextField();
        CodeField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        FindButton = new javax.swing.JButton();
        BottomPanel = new javax.swing.JPanel();
        TotalTextLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        DoneButton = new javax.swing.JButton();
        ScrollPane = new javax.swing.JScrollPane();
        SaleTable = new javax.swing.JTable();
        TopPanel = new javax.swing.JPanel();
        SwitchButton = new javax.swing.JButton();
        WelcomeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasse");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1374, 861));
        setPreferredSize(new java.awt.Dimension(1374, 861));

        BasePanel.setBackground(new java.awt.Color(255, 255, 255));
        BasePanel.setPreferredSize(new java.awt.Dimension(1050, 575));

        LeftPanel.setBackground(new java.awt.Color(255, 102, 102));
        LeftPanel.setMaximumSize(new java.awt.Dimension(200, 32767));
        LeftPanel.setMinimumSize(new java.awt.Dimension(200, 100));
        LeftPanel.setPreferredSize(new java.awt.Dimension(200, 575));

        Separator.setForeground(new java.awt.Color(255, 255, 255));

        TitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        TitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setText("Kasse");
        TitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        CodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        CodeLabel.setText("Codigo:");

        QuantityLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        QuantityLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuantityLabel.setText("Cantidad:");

        NameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("Nombre:");

        NameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        QuantityField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        CodeField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarRB.png"))); // NOI18N
        AddButton.setBorder(null);
        AddButton.setBorderPainted(false);
        AddButton.setMaximumSize(new java.awt.Dimension(200, 66));
        AddButton.setMinimumSize(new java.awt.Dimension(200, 66));
        AddButton.setPreferredSize(new java.awt.Dimension(200, 66));
        AddButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarRS.png"))); // NOI18N
        AddButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarRB.png"))); // NOI18N

        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSalirRB.png"))); // NOI18N
        LogoutButton.setBorder(null);
        LogoutButton.setBorderPainted(false);
        LogoutButton.setMaximumSize(new java.awt.Dimension(200, 66));
        LogoutButton.setMinimumSize(new java.awt.Dimension(200, 66));
        LogoutButton.setPreferredSize(new java.awt.Dimension(200, 66));
        LogoutButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSalirRS.png"))); // NOI18N
        LogoutButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSalirRB.png"))); // NOI18N
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonEliminarRB.png"))); // NOI18N
        DeleteButton.setBorder(null);
        DeleteButton.setBorderPainted(false);
        DeleteButton.setMaximumSize(new java.awt.Dimension(200, 66));
        DeleteButton.setMinimumSize(new java.awt.Dimension(200, 66));
        DeleteButton.setPreferredSize(new java.awt.Dimension(200, 66));
        DeleteButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonEliminarRS.png"))); // NOI18N
        DeleteButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonEliminarRB.png"))); // NOI18N

        FindButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonBuscarB.png"))); // NOI18N
        FindButton.setBorder(null);
        FindButton.setBorderPainted(false);
        FindButton.setMaximumSize(new java.awt.Dimension(200, 66));
        FindButton.setMinimumSize(new java.awt.Dimension(200, 66));
        FindButton.setPreferredSize(new java.awt.Dimension(200, 66));
        FindButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonBuscarS.png"))); // NOI18N
        FindButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonBuscarB.png"))); // NOI18N

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Separator))
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LeftPanelLayout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(TitleLabel))
                            .addGroup(LeftPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CodeLabel)
                                    .addComponent(QuantityLabel)
                                    .addComponent(NameLabel)
                                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(FindButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CodeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QuantityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        BottomPanel.setBackground(new java.awt.Color(255, 102, 102));

        TotalTextLabel.setBackground(new java.awt.Color(255, 255, 255));
        TotalTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TotalTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        TotalTextLabel.setText("Total: ");

        TotalLabel.setBackground(new java.awt.Color(255, 255, 255));
        TotalLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        TotalLabel.setText("0");

        DoneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonListoB.png"))); // NOI18N
        DoneButton.setBorder(null);
        DoneButton.setBorderPainted(false);
        DoneButton.setMaximumSize(new java.awt.Dimension(200, 66));
        DoneButton.setMinimumSize(new java.awt.Dimension(200, 66));
        DoneButton.setPreferredSize(new java.awt.Dimension(200, 66));
        DoneButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonListoS.png"))); // NOI18N
        DoneButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonListoB.png"))); // NOI18N

        javax.swing.GroupLayout BottomPanelLayout = new javax.swing.GroupLayout(BottomPanel);
        BottomPanel.setLayout(BottomPanelLayout);
        BottomPanelLayout.setHorizontalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomPanelLayout.createSequentialGroup()
                .addContainerGap(665, Short.MAX_VALUE)
                .addComponent(TotalTextLabel)
                .addGap(28, 28, 28)
                .addComponent(TotalLabel)
                .addGap(30, 30, 30)
                .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        BottomPanelLayout.setVerticalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DoneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomPanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        ScrollPane.setBorder(null);

        SaleTable.setAutoCreateRowSorter(true);
        SaleTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SaleTable.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        SaleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Índice", "Código", "Nombre", "Cantidad", "Precio", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SaleTable.setToolTipText("");
        SaleTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SaleTable.setGridColor(new java.awt.Color(255, 255, 255));
        SaleTable.setRowHeight(30);
        SaleTable.setSelectionBackground(new java.awt.Color(255, 153, 153));
        SaleTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SaleTable.getTableHeader().setReorderingAllowed(false);
        ScrollPane.setViewportView(SaleTable);
        if (SaleTable.getColumnModel().getColumnCount() > 0) {
            SaleTable.getColumnModel().getColumn(0).setResizable(false);
            SaleTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            SaleTable.getColumnModel().getColumn(1).setResizable(false);
            SaleTable.getColumnModel().getColumn(1).setPreferredWidth(1);
            SaleTable.getColumnModel().getColumn(2).setResizable(false);
            SaleTable.getColumnModel().getColumn(3).setResizable(false);
            SaleTable.getColumnModel().getColumn(4).setResizable(false);
            SaleTable.getColumnModel().getColumn(5).setResizable(false);
        }

        TopPanel.setBackground(new java.awt.Color(232, 80, 80));

        SwitchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSwitchRB.png"))); // NOI18N
        SwitchButton.setBorder(null);
        SwitchButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSwitchRDisable.png"))); // NOI18N
        SwitchButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSwitchRS.png"))); // NOI18N
        SwitchButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonSwitchRB.png"))); // NOI18N

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SwitchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SwitchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, Short.MAX_VALUE)
        );

        WelcomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        WelcomeLabel.setText("¡Bienvenido compañero Vendedor!");

        javax.swing.GroupLayout BasePanelLayout = new javax.swing.GroupLayout(BasePanel);
        BasePanel.setLayout(BasePanelLayout);
        BasePanelLayout.setHorizontalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasePanelLayout.createSequentialGroup()
                .addComponent(LeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BasePanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(WelcomeLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasePanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ScrollPane)
                        .addContainerGap())))
        );
        BasePanelLayout.setVerticalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeLabel)
                .addGap(12, 12, 12)
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1374, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JPanel BasePanel;
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JTextField CodeField;
    private javax.swing.JLabel CodeLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DoneButton;
    private javax.swing.JButton FindButton;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField QuantityField;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JTable SaleTable;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JSeparator Separator;
    private javax.swing.JButton SwitchButton;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel TotalTextLabel;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables

    public JButton getAddButton() {
        return AddButton;
    }

    public void setAddButton(JButton AddButton) {
        this.AddButton = AddButton;
    }

    public JPanel getBasePanel() {
        return BasePanel;
    }

    public void setBasePanel(JPanel BasePanel) {
        this.BasePanel = BasePanel;
    }

    public JPanel getBottomPanel() {
        return BottomPanel;
    }

    public void setBottomPanel(JPanel BottomPanel) {
        this.BottomPanel = BottomPanel;
    }

    public JTextField getCodeField() {
        return CodeField;
    }

    public void setCodeField(JTextField CodeField) {
        this.CodeField = CodeField;
    }

    public JLabel getCodeLabel() {
        return CodeLabel;
    }

    public void setCodeLabel(JLabel CodeLabel) {
        this.CodeLabel = CodeLabel;
    }

    public JButton getDeleteButton() {
        return DeleteButton;
    }

    public void setDeleteButton(JButton DeleteButton) {
        this.DeleteButton = DeleteButton;
    }

    public JButton getDoneButton() {
        return DoneButton;
    }

    public void setDoneButton(JButton DoneButton) {
        this.DoneButton = DoneButton;
    }

    public JButton getFindButton() {
        return FindButton;
    }

    public void setFindButton(JButton FindButton) {
        this.FindButton = FindButton;
    }

    public JPanel getLeftPanel() {
        return LeftPanel;
    }

    public void setLeftPanel(JPanel LeftPanel) {
        this.LeftPanel = LeftPanel;
    }

    public JButton getLogoutButton() {
        return LogoutButton;
    }

    public void setLogoutButton(JButton LogoutButton) {
        this.LogoutButton = LogoutButton;
    }

    public JTextField getNameField() {
        return NameField;
    }

    public void setNameField(JTextField NameField) {
        this.NameField = NameField;
    }

    public JLabel getNameLabel() {
        return NameLabel;
    }

    public void setNameLabel(JLabel NameLabel) {
        this.NameLabel = NameLabel;
    }

    public JTextField getQuantityField() {
        return QuantityField;
    }

    public void setQuantityField(JTextField QuantityField) {
        this.QuantityField = QuantityField;
    }

    public JLabel getQuantityLabel() {
        return QuantityLabel;
    }

    public void setQuantityLabel(JLabel QuantityLabel) {
        this.QuantityLabel = QuantityLabel;
    }

    public JTable getSaleTable() {
        return SaleTable;
    }

    public void setSaleTable(JTable SaleTable) {
        this.SaleTable = SaleTable;
    }

    public JScrollPane getScrollPane() {
        return ScrollPane;
    }

    public void setScrollPane(JScrollPane ScrollPane) {
        this.ScrollPane = ScrollPane;
    }

    public JSeparator getSeparator() {
        return Separator;
    }

    public void setSeparator(JSeparator Separator) {
        this.Separator = Separator;
    }

    public JButton getSwitchButton() {
        return SwitchButton;
    }

    public void setSwitchButton(JButton SwitchButton) {
        this.SwitchButton = SwitchButton;
    }

    public JLabel getTitleLabel() {
        return TitleLabel;
    }

    public void setTitleLabel(JLabel TitleLabel) {
        this.TitleLabel = TitleLabel;
    }

    public JPanel getTopPanel() {
        return TopPanel;
    }

    public void setTopPanel(JPanel TopPanel) {
        this.TopPanel = TopPanel;
    }

    public JLabel getTotalLabel() {
        return TotalLabel;
    }

    public void setTotalLabel(JLabel TotalLabel) {
        this.TotalLabel = TotalLabel;
    }

    public JLabel getTotalTextLabel() {
        return TotalTextLabel;
    }

    public void setTotalTextLabel(JLabel TotalTextLabel) {
        this.TotalTextLabel = TotalTextLabel;
    }

    public JLabel getWelcomeLabel() {
        return WelcomeLabel;
    }

    public void setWelcomeLabel(JLabel WelcomeLabel) {
        this.WelcomeLabel = WelcomeLabel;
    }
    
    

}
