/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextPane;
import javax.swing.JToggleButton;

/**
 *
 * @author l2001
 */
public class TicketView extends javax.swing.JFrame {

    /**
     * Creates new form VistaTicketKasse
     */
    public TicketView() {
        initComponents();
        // this.setExtendedState(0);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/Fuente.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BasePanel = new javax.swing.JPanel();
        StoreNameLabel = new javax.swing.JLabel();
        Icono = new javax.swing.JLabel();
        RFCLabel = new javax.swing.JLabel();
        PlaceLabel = new javax.swing.JLabel();
        StateLabel = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        ListContent = new javax.swing.JTextPane();
        Separator = new javax.swing.JSeparator();
        GenerateButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        BasePanel.setBackground(new java.awt.Color(255, 255, 255));

        StoreNameLabel.setText("Abarrotes Doña Yolis");

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fuente.png"))); // NOI18N

        RFCLabel.setText("R.F.C           TK1821873-RMC-ASA ");

        PlaceLabel.setText("Colonia Francisco de Montejo\t    CP 97203 \t");

        StateLabel.setText("Mérida Yucatán");

        ListContent.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ListContent.setAutoscrolls(false);
        ListContent.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ScrollPane.setViewportView(ListContent);

        GenerateButton.setText("Generar");
        GenerateButton.setBorder(null);
        GenerateButton.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout BasePanelLayout = new javax.swing.GroupLayout(BasePanel);
        BasePanel.setLayout(BasePanelLayout);
        BasePanelLayout.setHorizontalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasePanelLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasePanelLayout.createSequentialGroup()
                        .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasePanelLayout.createSequentialGroup()
                        .addComponent(Icono, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasePanelLayout.createSequentialGroup()
                        .addGroup(BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RFCLabel)
                            .addGroup(BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PlaceLabel)
                                .addGroup(BasePanelLayout.createSequentialGroup()
                                    .addComponent(StateLabel)
                                    .addGap(88, 88, 88))))
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasePanelLayout.createSequentialGroup()
                        .addComponent(GenerateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasePanelLayout.createSequentialGroup()
                        .addComponent(StoreNameLabel)
                        .addGap(214, 214, 214))))
        );
        BasePanelLayout.setVerticalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StoreNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenerateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Icono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RFCLabel)
                .addGap(18, 18, 18)
                .addComponent(PlaceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StateLabel)
                .addGap(18, 18, 18)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasePanel;
    private javax.swing.JToggleButton GenerateButton;
    private javax.swing.JLabel Icono;
    private javax.swing.JTextPane ListContent;
    private javax.swing.JLabel PlaceLabel;
    private javax.swing.JLabel RFCLabel;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JSeparator Separator;
    private javax.swing.JLabel StateLabel;
    private javax.swing.JLabel StoreNameLabel;
    // End of variables declaration//GEN-END:variables

    public JPanel getBasePanel() {
        return BasePanel;
    }

    public void setBasePanel(JPanel BasePanel) {
        this.BasePanel = BasePanel;
    }

    public JToggleButton getGenerateButton() {
        return GenerateButton;
    }

    public void setGenerateButton(JToggleButton GenerateButton) {
        this.GenerateButton = GenerateButton;
    }

    public JLabel getIcono() {
        return Icono;
    }

    public void setIcono(JLabel Icono) {
        this.Icono = Icono;
    }

    public JTextPane getListContent() {
        return ListContent;
    }

    public void setListContent(JTextPane ListContent) {
        this.ListContent = ListContent;
    }

    public JLabel getPlaceLabel() {
        return PlaceLabel;
    }

    public void setPlaceLabel(JLabel PlaceLabel) {
        this.PlaceLabel = PlaceLabel;
    }

    public JLabel getRFCLabel() {
        return RFCLabel;
    }

    public void setRFCLabel(JLabel RFCLabel) {
        this.RFCLabel = RFCLabel;
    }

    public JScrollPane getScrollPane() {
        return ScrollPane;
    }

    public void setScrollPane(JScrollPane ScrollPane) {
        this.ScrollPane = ScrollPane;
    }

    public JSeparator getSeparator() {
        return Separator;
    }

    public void setSeparator(JSeparator Separator) {
        this.Separator = Separator;
    }

    public JLabel getStateLabel() {
        return StateLabel;
    }

    public void setStateLabel(JLabel StateLabel) {
        this.StateLabel = StateLabel;
    }

    public JLabel getStoreNameLabel() {
        return StoreNameLabel;
    }

    public void setStoreNameLabel(JLabel StoreNameLabel) {
        this.StoreNameLabel = StoreNameLabel;
    }
    
}
